require-module prelude
require-module connect

add-highlighter global/ number-lines
#add-highlighter global show-matching

set-option global tabstop 2
set-option global aligntab true

map global normal <c-n> j
map global normal <c-p> k
map global normal <c-t> :easy-motion-char<ret>

map global normal <c-b> ':enter-user-mode buffers<ret>'
map global normal <c-B> ':enter-user-mode -lock buffers<ret>'

map global normal <c-g> ':comment-line<ret>'
